//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageDetail
    {
        public int PackageDetailsID { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
    }
}
