//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raw_Data
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<double> ZipCode { get; set; }
        public string County { get; set; }
        public string Gender { get; set; }
        public string Birthday { get; set; }
        public string Ethnicity { get; set; }
        public Nullable<double> Desi { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> EthnicityID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
    }
}
